# -*- coding: utf-8 -*-
"""EX1 - M2 - AD

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1evzsCdnXcS4ZUbN8EeDeerEYf00TNpja

Lista Top 10 filmes IMDB
"""

top_10_imdb = ['Um Sonho de Liberdade', 'O Poderoso Chefão', 'Batman: O Cavaleiro das Trevas', 'O Poderoso Chefão II', '12 Homens e uma Sentença', 'A Lista de Schindler','O Senhor dos Anéis: O Retorno do Rei','Pulp Fiction - Tempo de Violência','O Senhor dos Anéis: A Sociedade do Anel','Três Homens em Conflito']

#insert

top_10_imdb.insert (1,'Cinderela baiana')

#pop

top_10_imdb.pop(0)

print (top_10_imdb)